// Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
    "github.com/swaggo/swag"
    "project/handlers"
    
)
    

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user/add": {
            "post": {
                summary: Add new user,
                "tags":[
                    User
                ],
                produces: [
					application/json
				],
                parameters: [
                    {
                        name: add user,
                        in: body,   
                        description: Register new user,
                        "properties":{
                            username:{
                                type:string,
                                format:json
                            },
                            email:{
                                type:string,
                                format:json
                            },
                            password:{
                                type:string,
                                format:json
                            },
                        },
			        },
			    ],
                responses: {
					200: {
						description: Status, OK
					}
				}
            },
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:"+handlers.DotEnvVariable("SERVER_PORT"),
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "FH_Project",
	Description:      "Swagger for FH_Project",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
